name: mirror

on:
  push:
    branches:
      - main
  pull_request:

env:
  regclient_version: v0.4.5

jobs:
  copy:
    strategy:
      fail-fast: false
      matrix:
        image:
          - debian:stable
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - run: curl -L -o regctl 'https://github.com/regclient/regclient/releases/${{ env.regclient_version }}/download/regctl-linux-amd64'
      - run: chmod 755 regctl
      - run: ./regctl version

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: ./regctl image copy '${{ matrix.image }}' 'ghcr.io/${{ github.repository }}/${{ matrix.image }}'
